version: 2

sources:
  - name: raw
    schema: RAW
    tables:
      - name: customers

      - name: orders
        columns:
          - name: customer_id
            tests:
              - relationships:
                  to: source('raw', 'customers')
                  field: customer_id